development:
  cloud_name: dnkiqjdfl
  api_key: '252949358125123'
  api_secret: owDmpsd5LF8adJogeSecXLoJXjU
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dnkiqjdfl
  api_key: '252949358125123'
  api_secret: owDmpsd5LF8adJogeSecXLoJXjU
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dnkiqjdfl
  api_key: '252949358125123'
  api_secret: owDmpsd5LF8adJogeSecXLoJXjU
  enhance_image_tag: true
  static_file_support: false